""" Euler Problem #2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

max = 4000000
sumn = 0
# a и b - переменные, которые будут меняться на различные члены ряда фибоначчи
a = 1
b = 2
# пока число фибоначчи не превышает 4 миллиона выполняется цикл
while a <= max:
    # если число больше 4 миллионов - выходим из цикла
    if (a % 2 == 0) and a >= max and (b % 2 == 0) and b >= max:
        break
    # проверяем на четность и добавляем в сумму
    if (a % 2 == 0):
        sumn += a
    # проверяем на четность и добавляем в сумму
    if (b % 2 == 0):
        sumn += b
    # продолжаем ряд фибоначчи
    a = a + b
    b = a + b

print(sumn)
