"""Euler Problem #45:
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

def find(number, lst):
    try:
        lst.index(number)
        return 0
    except ValueError:
        return 1




triangles_numbers_lst = []
for number_trinagles in range(1, 100000):
    triangles_numbers_lst.append(int((number_trinagles*(number_trinagles + 1))/2))

pentagonals_numbers_lst = []
for number_pentagonals in range(1, 100000):
    pentagonals_numbers_lst.append(int((number_pentagonals*(3*number_pentagonals - 1))/2))

hexagonals_numbers_lst = []
for number_hexagonals in range(1, 100000):
    hexagonals_numbers_lst.append(int((number_hexagonals*(2*number_hexagonals - 1))))



for number in triangles_numbers_lst:
    if find(number, pentagonals_numbers_lst) == 0 and find(number, hexagonals_numbers_lst) == 0:
       print(number, triangles_numbers_lst.index(number) + 1)
